version: '3.3'

services:
  web:
    build: ./.
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./www/:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - ./.env.dev
